[build]
  # Since this is a static HTML site, no build command is needed
  publish = "."
  
[build.environment]
  # Environment variables (if needed in the future)
  NODE_VERSION = "18"

[[redirects]]
  # Domain canonicalization - Force HTTPS and WWW
  from = "http://faizanbc.com/*"
  to = "https://www.faizanbc.com/:splat"
  status = 301
  force = true

[[redirects]]
  from = "https://faizanbc.com/*"
  to = "https://www.faizanbc.com/:splat"
  status = 301
  force = true

[[redirects]]
  from = "http://www.faizanbc.com/*"
  to = "https://www.faizanbc.com/:splat"
  status = 301
  force = true

# SPA routing for clean URLs
[[redirects]]
  from = "/about"
  to = "/index.html"
  status = 200

[[redirects]]
  from = "/services"
  to = "/index.html"
  status = 200

[[redirects]]
  from = "/projects"
  to = "/index.html"
  status = 200

[[redirects]]
  from = "/reviews"
  to = "/index.html"
  status = 200

[[redirects]]
  from = "/contact"
  to = "/index.html"
  status = 200

[[redirects]]
  from = "/portfolio"
  to = "/index.html"
  status = 200

# Redirect old hash URLs to clean URLs
[[redirects]]
  from = "/#about"
  to = "/about"
  status = 301

[[redirects]]
  from = "/#services"
  to = "/services"
  status = 301

[[redirects]]
  from = "/#projects"
  to = "/projects"
  status = 301

[[redirects]]
  from = "/#reviews"
  to = "/reviews"
  status = 301

[[redirects]]
  from = "/#contact"
  to = "/contact"
  status = 301

# Fallback for SPA
[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200

[build.processing]
  skip_processing = false

[build.processing.css]
  bundle = true
  minify = true

[build.processing.js]
  bundle = true
  minify = true

[build.processing.html]
  pretty_urls = true

[[headers]]
  for = "/*"
  [headers.values]
    X-Frame-Options = "DENY"
    X-XSS-Protection = "1; mode=block"
    X-Content-Type-Options = "nosniff"
    Referrer-Policy = "strict-origin-when-cross-origin"
    Permissions-Policy = "camera=(), microphone=(), geolocation=()"

[[headers]]
  for = "/*.css"
  [headers.values]
    Cache-Control = "public, max-age=31536000"

[[headers]]
  for = "/*.js"
  [headers.values]
    Cache-Control = "public, max-age=31536000"

[[headers]]
  for = "/*.png"
  [headers.values]
    Cache-Control = "public, max-age=31536000"

[[headers]]
  for = "/*.jpg"
  [headers.values]
    Cache-Control = "public, max-age=31536000"

[[headers]]
  for = "/*.jpeg"
  [headers.values]
    Cache-Control = "public, max-age=31536000"
